# Generated by Django 2.2.6 on 2021-11-05 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20211105_0711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post2',
            new_name='Post1',
        ),
    ]
