# Generated by Django 2.2.6 on 2021-11-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
